version: '3.8'

services:
  tmdb_web:
    image: lifailon/froxy
    environment:
      SOCKS: "0"
      FORWARD: "0"
      LOCAL: "*:8001"
      REMOTE: "https://themoviedb.org"
      USER: "false"
      PASSWORD: "false"
    ports:
      - "8001:8001"

  tmdb_api:
    image: lifailon/froxy
    environment:
      SOCKS: "0"
      FORWARD: "0"
      LOCAL: "*:8002"
      REMOTE: "https://api.themoviedb.org"
      USER: "false"
      PASSWORD: "false"
    ports:
      - "8002:8002"